name: 'Setup project'
description: 'Checkout, setup php, composer install'
inputs:
  php-version:
    description: 'Php version'
    required: false
    default: '8.2'
  install-dev-dependencies:
    description: 'Install dev dependencies'
    required: false
    default: 'false'
runs:
  using: composite
  steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ inputs.php-version }}
        extensions: ctype, dom, iconv

    - name: Cache vendor (with dev)
      if: ${{ inputs.install-dev-dependencies == 'true' }}
      uses: actions/cache@v4
      with:
          path: vendor
          key: ${{ runner.os }}-vendor-dev-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
              ${{ runner.os }}-vendor-no-dev-${{ hashFiles('**/composer.lock') }}
              ${{ runner.os }}-vendor-dev
              ${{ runner.os }}-vendor-no-dev
              ${{ runner.os }}-vendor


    - name: Install dependencies (with dev)
      if: ${{ inputs.install-dev-dependencies == 'true' }}
      shell: bash
      run: composer install --prefer-dist --no-progress

    - name: Cache vendor (without dev)
      if: ${{ inputs.install-dev-dependencies == 'false' }}
      uses: actions/cache@v4
      with:
          path: vendor
          key: ${{ runner.os }}-vendor-no-dev-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
              ${{ runner.os }}-vendor-dev-${{ hashFiles('**/composer.lock') }}
              ${{ runner.os }}-vendor-no-dev
              ${{ runner.os }}-vendor-dev
              ${{ runner.os }}-vendor

    - name: Install dependencies (without dev)
      if: ${{ inputs.install-dev-dependencies == 'false' }}
      shell: bash
      run: composer install --prefer-dist --no-progress --no-dev

