name: Code quality

on:
    push:
        branches: ["main"]
    pull_request:

permissions:
    contents: write

jobs:
    composer:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Validate composer.json and composer.lock
              run: composer validate --strict

    composerAudit:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-versions }}
                  extensions: ctype, dom, iconv
                  coverage: none
            - name: Install dependencies
              run: composer install --prefer-dist --no-progress
            - name: Run composer audit
              uses: alamirault/composer-audit-action@v1

    phpstan:
        name: PHPStan
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-versions: ['8.2', '8.3']
            fail-fast: false
        steps:
            - uses: actions/checkout@v4
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ matrix.php-versions }}
                  extensions: ctype, dom, iconv
                  coverage: none
            - name: Install dependencies
              run: composer install --prefer-dist --no-progress
            - name: Execute PHPStan
              uses: php-actions/phpstan@v3
              with:
                  level: 7
                  path: bin config public src tests

    php-cs-fixer:
        name: PHP CS Fixer
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup PHP
              uses: shivammathur/setup-php@v5
              with:
                  php-version: ${{ matrix.php-versions }}
                  extensions: ctype, dom, iconv
                  coverage: none
            - name: Install dependencies
              run: composer install --prefer-dist --no-progress
            - name: Run PHP-CS-Fixer Style
              run: ./vendor/bin/php-cs-fixer fix
            - uses: stefanzweifel/git-auto-commit-action@v4
              with:
                commit_message: Apply PHP-CS-Fixer changes

    phpunit:
        name: PHPUnit
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-versions: ['8.2', '8.3']
            fail-fast: false
        steps:
            -   uses: actions/checkout@v4
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-versions }}
                    extensions: ctype, dom, iconv
            -   name: Install dependencies
                run: composer install --prefer-dist --no-progress
            -   name: Execute PHPUnit
                run: vendor/bin/phpunit --coverage-clover ./coverage.xml
                env:
                    XDEBUG_MODE: coverage
            -   name: Upload to Codecov
                uses: codecov/codecov-action@v4
                with:
                    token: ${{ secrets.CODE_COV_TOKEN }}
                    files: ./coverage.xml
                    verbose: true
