name: Code cleanup

on:
  push:
    branches: ["main"]
  pull_request:

permissions:
  contents: write

jobs:
  cleanup:
    name: Code cleanup
    runs-on: ubuntu-latest
    env:
      HAVE_PERSONNAL_ACCESS_TOKEN: ${{ secrets.PERSONNAL_ACCESS_TOKEN != '' }}
    steps:
      - uses: actions/checkout@v4
        if: ${{ env.HAVE_PERSONNAL_ACCESS_TOKEN == 'true' }}
        with:
            token: ${{ secrets.PERSONNAL_ACCESS_TOKEN }}
      - uses: actions/checkout@v4
        if: ${{ env.HAVE_PERSONNAL_ACCESS_TOKEN != 'true' }}
      - uses: ./.github/actions/setup
        with:
          install-dev-dependencies: true
      - name: Execute Rector
        run: vendor/bin/rector process --ansi
      - name: Execute PHP CS Fixer
        run: vendor/bin/php-cs-fixer fix
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: Apply Rector / PHP CS Fixer changes
