name: Tests

on:
    push:
        branches: ["main"]
    pull_request:

permissions:
    contents: write

jobs:
    composer:
        name: Composer validate
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Validate composer.json and composer.lock
              run: composer validate --strict

    composerAudit:
        name: Composer audit
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.2'
                  extensions: ctype, dom, iconv
                  coverage: none
            - name: Install dependencies
              run: composer install --prefer-dist --no-progress
            - name: Run composer audit
              uses: alamirault/composer-audit-action@v1

    phpstan:
        name: PHPStan
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '8.2'
                  extensions: ctype, dom, iconv
                  coverage: none

            -   name: Cache vendor
                uses: actions/cache@v4
                with:
                    path: vendor
                    key: ${{ runner.os }}-vendor-${{ matrix.php-versions }}-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-vendor-${{ matrix.php-versions }}
                        ${{ runner.os }}-vendor
            - name: Install dependencies
              run: composer install --prefer-dist --no-progress
            - name: Execute PHPStan
              run: ./vendor/bin/phpstan

    phpunit:
        name: PHPUnit
        runs-on: ubuntu-latest
        strategy:
            matrix:
                php-versions: ['8.2', '8.3']
            fail-fast: false
        steps:
            -   uses: actions/checkout@v4
            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php-versions }}
                    extensions: ctype, dom, iconv

            -   name: Cache vendor
                uses: actions/cache@v4
                with:
                    path: vendor
                    key: ${{ runner.os }}-vendor-${{ matrix.php-versions }}-${{ hashFiles('**/composer.lock') }}
                    restore-keys: |
                        ${{ runner.os }}-vendor-${{ matrix.php-versions }}
                        ${{ runner.os }}-vendor

            -   name: Install dependencies
                run: composer install --prefer-dist --no-progress
            -   name: Execute PHPUnit
                run: vendor/bin/phpunit --coverage-clover ./coverage.xml
                env:
                    XDEBUG_MODE: coverage
            -   name: Upload to Codecov
                if: ${{ matrix.php-versions == '8.2' }}
                uses: codecov/codecov-action@v4
                with:
                    token: ${{ secrets.CODE_COV_TOKEN }}
                    files: ./coverage.xml
                    verbose: true
